### ISSUE TITLE
Remove donation details from readme

### ISSUE THREAD

**Issue by arshadkazmi42** [gh-conf/gh-conf-response#19]
- Remove `Buy me a coffee` badge
- Remove `Become a Patron` badge
- Remove `Please consider donating, if you like my work`

**Comment by sleekyom** [comment]
Can I take this?

**Comment by arshadkazmi42** [comment]
@sleekyom Sure go ahead, send a PR

**Comment by sleekyom** [comment]
Will do that shortly

**Comment by arshadkazmi42** [comment]
Fixed in #20

**Comment by sleekyom** [comment]
it's done now
