### ISSUE TITLE
Add badges in README

### ISSUE THREAD

**Issue by arshadkazmi42** [gh-conf/gh-conf-response#3]
Add badges similar to [flip-remote](https://github.com/arshadkazmi42/flip-remote#flip-remote-octocat)

**Comment by ramstore07** [comment]
Hey there! need help with that?

**Comment by ramstore07** [comment]
Hey there! If you added badges already, please mark request as complete. :)

**Comment by arshadkazmi42** [comment]
Thank  you for reminding 👍

**Comment by arshadkazmi42** [comment]
@ramstore07 We have a similar issue in another repository if you are interested
https://github.com/gh-conf/gh-conf-validate/issues/1
